# Site settings
title: Analogweb Framework
email:  
description: > # this means to ignore newlines until "baseurl:"
  Analogweb is a tiny, simple, and pluggable web framework in Scala.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/analogweb" # the base hostname & protocol for your site
twitter_username: 
github_username: analogweb 

# Build settings
markdown: kramdown
