title: Analogweb
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Analogweb is tiny, simple, and pluggable web framework for Scala.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://analogweb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  analogweb

# Build settings
markdown: kramdown
theme: minima
